// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppMenu: typeof import('./src/components/app/AppMenu.vue')['default']
    Footer: typeof import('./src/components/app/Footer.vue')['default']
    InteractionCore: typeof import('./src/components/InteractionCore.vue')['default']
    MiniHeader: typeof import('./src/components/MiniHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Submenu: typeof import('./src/components/app/Submenu.vue')['default']
    Topbar: typeof import('./src/components/app/Topbar.vue')['default']
  }
}
